/**
 * Color Set Protocol (CSP) - SCSS Generator
 * Generates SCSS maps and files from resolved color sets
 */

import type { ResolvedColorSet, ResolvedColorTokens, OutputOptions } from '../schema';

/**
 * Generate an SCSS map from resolved tokens
 */
export function generateSCSSMap(
  tokens: ResolvedColorTokens,
  mapName: string,
  options: OutputOptions = {}
): string {
  const { includeComments = false } = options;

  const lines: string[] = [];

  if (includeComments) {
    lines.push(`// Color tokens map: ${mapName}`);
  }

  lines.push(`$${mapName}: (`);

  for (const [name, value] of Object.entries(tokens)) {
    lines.push(`  '${name}': ${value},`);
  }

  lines.push(');');

  return lines.join('\n');
}

/**
 * Generate SCSS variable declarations (flat, not a map)
 */
export function generateSCSSVariables(
  tokens: ResolvedColorTokens,
  prefix: string = 'color',
  options: OutputOptions = {}
): string {
  const { includeComments = false } = options;

  const lines: string[] = [];

  if (includeComments) {
    lines.push(`// Color variables with prefix: ${prefix}`);
  }

  for (const [name, value] of Object.entries(tokens)) {
    // Convert kebab-case to kebab-case (just add prefix)
    const varName = `${prefix}-${name}`;
    lines.push(`$${varName}: ${value};`);
  }

  return lines.join('\n');
}

/**
 * Generate a complete SCSS color set file
 */
export function generateSCSSColorSet(
  resolved: ResolvedColorSet,
  options: OutputOptions = {}
): string {
  const { includeComments = true } = options;

  const lines: string[] = [];
  const mapName = `color-set-${resolved.id}`;

  if (includeComments) {
    lines.push('// ===================');
    lines.push(`// Theme: ${resolved.name}`);
    lines.push('// ===================');
    lines.push(`// Mode: ${resolved.mode}`);
    lines.push(`// Generated by Color Set Protocol (CSP)`);
    lines.push('');
  }

  lines.push(generateSCSSMap(resolved.tokens, mapName, { includeComments: false }));

  return lines.join('\n');
}

/**
 * Generate a complete SCSS file with all color sets
 */
export function generateSCSSFile(
  themes: ResolvedColorSet[],
  options: OutputOptions = {}
): string {
  const lines: string[] = [];

  lines.push('// ===================');
  lines.push('// Color Sets Definition');
  lines.push('// ===================');
  lines.push('// Generated by Color Set Protocol (CSP)');
  lines.push('// Do not edit manually');
  lines.push('');
  lines.push("@use 'sass:map';");
  lines.push('');

  for (const theme of themes) {
    lines.push(generateSCSSColorSet(theme, options));
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Generate SCSS that outputs CSS custom properties
 * This creates a mixin that can be used to output theme variables
 */
export function generateSCSSMixin(
  resolved: ResolvedColorSet,
  options: OutputOptions = {}
): string {
  const { prefix = 'wg-color' } = options;
  const mixinName = `theme-${resolved.id}`;

  const lines: string[] = [];

  lines.push(`@mixin ${mixinName}() {`);

  for (const [name, value] of Object.entries(resolved.tokens)) {
    lines.push(`  --${prefix}-${name}: ${value};`);
  }

  lines.push('}');

  return lines.join('\n');
}

/**
 * Generate SCSS with theme mixins for all color sets
 */
export function generateSCSSThemeMixins(
  themes: ResolvedColorSet[],
  options: OutputOptions = {}
): string {
  const lines: string[] = [];

  lines.push('// ===================');
  lines.push('// Theme Mixins');
  lines.push('// ===================');
  lines.push('// Generated by Color Set Protocol (CSP)');
  lines.push('');

  for (const theme of themes) {
    lines.push(`// Theme: ${theme.name} (${theme.mode})`);
    lines.push(generateSCSSMixin(theme, options));
    lines.push('');
  }

  // Add convenience mixin to apply all themes
  lines.push('// Apply all themes');
  lines.push('@mixin all-themes() {');
  lines.push('  :root {');
  const defaultTheme = themes.find((t) => t.id === 'default');
  if (defaultTheme) {
    lines.push(`    @include theme-${defaultTheme.id}();`);
  }
  lines.push('  }');
  lines.push('');

  for (const theme of themes) {
    if (theme.id !== 'default') {
      lines.push(`  [data-theme="${theme.id}"] {`);
      lines.push(`    @include theme-${theme.id}();`);
      lines.push('  }');
      lines.push('');
    }
  }

  lines.push('}');

  return lines.join('\n');
}
