import type { ComponentDefinition } from '../types';
import { filterNullish } from '../types';

/** Checkbox size options */
export const CheckboxSizes = ['sm', 'md', 'lg'] as const;
export type CheckboxSize = (typeof CheckboxSizes)[number];

/** Style props for Checkbox component */
export interface CheckboxStyleProps {
  size?: CheckboxSize;
  checked?: boolean;
  indeterminate?: boolean;
  disabled?: boolean;
}

/** DOM attributes generated by Checkbox */
export interface CheckboxAttrs {
  class: string;
  'data-size': CheckboxSize;
  'data-state': 'unchecked' | 'checked' | 'indeterminate' | 'disabled';
}

/** Checkbox component definition */
export const Checkbox = {
  displayName: 'Checkbox',

  defaultProps: {
    size: 'md',
    checked: false,
    indeterminate: false,
    disabled: false,
  },

  propTypes: {
    size: CheckboxSizes,
  },

  mapPropsToAttrs: (props: CheckboxStyleProps): CheckboxAttrs => {
    const merged = { ...Checkbox.defaultProps, ...filterNullish(props) };
    const state = merged.disabled
      ? 'disabled'
      : merged.indeterminate
      ? 'indeterminate'
      : merged.checked
      ? 'checked'
      : 'unchecked';
    return {
      class: 'checkbox',
      'data-size': merged.size,
      'data-state': state,
    };
  },

  template: {
    tag: 'div',
    slots: ['default'],
  },
} as const satisfies ComponentDefinition<CheckboxStyleProps, CheckboxAttrs, 'div'>;
