import type { ComponentDefinition } from '../types';
import { filterNullish } from '../types';

/** Input variant options */
export const InputVariants = ['outline', 'filled', 'underline'] as const;
export type InputVariant = (typeof InputVariants)[number];

/** Input size options */
export const InputSizes = ['sm', 'md', 'lg'] as const;
export type InputSize = (typeof InputSizes)[number];

/** Style props for Input component */
export interface InputStyleProps {
  variant?: InputVariant;
  size?: InputSize;
  error?: boolean;
  success?: boolean;
  disabled?: boolean;
}

/** DOM attributes generated by Input */
export interface InputAttrs {
  class: string;
  'data-variant': InputVariant;
  'data-size': InputSize;
  'data-state'?: 'error' | 'success' | 'disabled' | undefined;
  disabled?: boolean | undefined;
}

/** Input component definition */
export const Input = {
  displayName: 'Input',

  defaultProps: {
    variant: 'outline',
    size: 'md',
    error: false,
    success: false,
    disabled: false,
  },

  propTypes: {
    variant: InputVariants,
    size: InputSizes,
  },

  mapPropsToAttrs: (props: InputStyleProps): InputAttrs => {
    const merged = { ...Input.defaultProps, ...filterNullish(props) };
    const state = merged.error ? 'error' : merged.success ? 'success' : merged.disabled ? 'disabled' : undefined;
    return {
      class: 'input',
      'data-variant': merged.variant,
      'data-size': merged.size,
      'data-state': state,
      disabled: merged.disabled || undefined,
    };
  },

  template: {
    tag: 'input',
    slots: [],
  },
} as const satisfies ComponentDefinition<InputStyleProps, InputAttrs, 'input'>;
